apiVersion: v1
kind: Service
metadata:
  name: app-backend
  annotations:
    kubernetes.digitalocean.com/healthcheck-protocol: "http"
    kubernetes.digitalocean.com/healthcheck-path: "/healthz"
    kubernetes.digitalocean.com/healthcheck-port: "8000"
spec:
  type: ClusterIP
  selector:
    app: app-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000