resources:
  - ../../backend/deployment.yaml
  - ../../backend/service.yaml
  - ../../frontend/deployment.yaml
  - ../../frontend/service.yaml
images:
  - name: app-backend
    newName: ghcr.io/wenxuanwangut/app-backend
    newTag: latest
  - name: app-frontend
    newName: ghcr.io/wenxuanwangut/app-frontend
    newTag: latest
patches:
  - path: deployment-backend-patch.yaml
  - path: deployment-frontend-patch.yaml