resources:
  - ../../backend/deployment.yaml
  - ../../backend/service.yaml
  - ../../frontend/deployment.yaml
  - ../../frontend/service.yaml
images:
  - name: app-backend
    newName: docker.io/penguinofmadagascar/app-backend
    newTag: release
  - name: app-frontend
    newName: docker.io/penguinofmadagascar/app-frontend
    newTag: release
patches:
  - path: deployment-backend-patch.yaml
  - path: deployment-frontend-patch.yaml