resources:
  - ../../deployment.yaml
  - ../../service.yaml
  - ../../frontend/deployment.yaml
  - ../../frontend/service.yaml
images:
  - name: app-backend
    newName: ghcr.io/wenxuanwangut/app-backend
    newTag: REPLACED_BY_CI
  - name: app-frontend
    newName: ghcr.io/wenxuanwangut/app-frontend
    newTag: REPLACED_BY_CI
patches:
  - path: deployment-backend-patch.yaml
  - path: deployment-frontend-patch.yaml