apiVersion: v1
kind: Service
metadata:
  name: app-frontend
  annotations:
    kubernetes.digitalocean.com/healthcheck-protocol: "http"
    kubernetes.digitalocean.com/healthcheck-path: "/healthz"
    kubernetes.digitalocean.com/healthcheck-port: "80"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080