# docker run -d --name cloudcollab-prom -p 9090:9090 -v $PWD/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus
# docker run -d --name cloudcollab-grafana -p 3000:3000 grafana/grafana
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "cloudcollab-backend"
    scheme: https
    metrics_path: /api/metrics
    static_configs:
      - targets:
          - cloudcollab-ufhp2.ondigitalocean.app